import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideMenu from '../components/layouts/sideMenu'
import TopMenu from '../components/layouts/topMenu'
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PTT Smart Check Sheet",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <div className="lg:hidden h-screen w-full flex flex-col justify-center items-center text-blue-400">
        <div>
          <Image
            src={'/images/logo.png'}
            alt=''
            width={100}
            height={100}
          />
        </div>
        <div className="text-center w-[300px]">  Mobile version is developing, You can try with  Desktop</div>
      </div>
      <body className="hidden lg:block">
        <TopMenu />
        <div className="flex">
          <SideMenu />
          <div className="p-5 w-full max-h-[90vh] overflow-y-scroll">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
