import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideMenu from '../components/layouts/sideMenu'
import TopMenu from '../components/layouts/topMenu'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PTT Smart Check Sheet",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <TopMenu />
        <div className="flex">
          <SideMenu />
          <div className="p-5 w-full">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
